### ISSUE TITLE
Set proper title and favicon of tool

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/ferret#80]
Right now it uses the file name that's being loaded, though that looks weird: 
![image](https://user-images.githubusercontent.com/2039375/149334402-a76f09dc-b2a9-42a2-9be5-196554bf3877.png)

Maybe have a project name? 

As for icon, maybe something like this? 

https://www.tasmeemme.com/en/store-items/ferret-element-in-flat-simple-style-on-white-background-ferret-icon-with-text-name-concept-template/?item=10133700683

https://dribbble.com/shots/6948134-Ferret

https://dribbble.com/shots/2000946-mr-Ferret 

You can either buy rights to these if it's available, or use it as inspiration and do something with it in e.g., illustrator? Feel free to ask for help from e.g., Jen.

**Comment by alexsb** [comment]
https://fontawesome.com/v5.15/icons/otter?style=solid

**Comment by Dev-Lan** [comment]
/For the title, what about  "Ferret: <filename>", in this case "Ferret: Glioma.csv", and drop the folders. I do like including some indication of the file since you can upload your own files.

Maybe there is somewhere else that should be added instead of the title?

**Comment by alexsb** [comment]
We don't have to use "Ferret" if we have a nice icon. Yes, just the file name would help and probably be good enough. I was thinking we could also have a user specified project name, but that might be overkill.
