### ISSUE TITLE
Refactor for Dimension Selection

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/ferret#83]
The dimension selector could be a bit nicer: 
![image](https://user-images.githubusercontent.com/2039375/149362593-fbadba0a-8195-4142-b9e9-32ba7973b3a8.png)

1) show the data type (numerical, categorical, label)
2) space between the checkbox and the label
3) the blue tick is pretty "intense" here.  Maybe make it gray? Or make it a toggle?

**Comment by Dev-Lan** [comment]
Related to #56
