### ISSUE TITLE
Improve spacing for buttons

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/ferret#86]
They aren't properly centered: 

![image](https://user-images.githubusercontent.com/2039375/149363933-631638db-8025-4269-a8b6-6cdc184530ec.png)

**Comment by Dev-Lan** [comment]
Do you just mean the ignore and highlight buttons?

**Comment by alexsb** [comment]
I mean vertical layout. The horizontal layout of those are also off; yes, but might be irrelevant if we do #87

**Comment by alexsb** [comment]
This isn't solved on my computer (did a hard reload and clear cache), though it's weird: 

![image](https://user-images.githubusercontent.com/2039375/149502689-66e5fcc3-22d5-4fd2-b4ad-a5e0e812c8d3.png)

The tool bar div is bigger that what's highlighted when I inspect the element, and I also don't see padding etc. 

I

**Comment by alexsb** [comment]
Ah, I get it now; the gray background is just for the whole window, that's not part of the toolbar. 

This fixes it: 

![image](https://user-images.githubusercontent.com/2039375/149503263-e580eedc-732b-4ab8-9e1e-6d8eb8e354ad.png)

margin-top: 5px; there's a margin-top 5px in the main div, and that was throwing it off. 

I've also added a margin-left

The left container needs to also be updated.

**Comment by Dev-Lan** [comment]
I see what you mean now. I thought you mean the text within the buttons, not the buttons within the toolbar.
